# Generated by Django 5.1 on 2024-11-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_login_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
