# Generated by Django 5.1 on 2024-11-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_customuser_first_login_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_login_date',
        ),
    ]
