# Generated by Django 5.1.1 on 2024-09-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
