# Generated by Django 5.1.1 on 2024-09-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('task_manager', '0004_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='task_manage_email_4ad25d_idx'),
        ),
    ]
