# Generated by Django 5.1 on 2025-01-23 14:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_departmentmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentTaskType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_tasks', to='task_manager.department')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_tasks', to='task_manager.tasktype')),
            ],
            options={
                'unique_together': {('department', 'task')},
            },
        ),
    ]
