# Generated by Django 5.1 on 2025-02-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_departmenttasktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='stage',
            field=models.CharField(choices=[('PD', 'ПД'), ('RD', 'РД'), ('OTR', 'ОТР'), ('-', '-')], max_length=255),
        ),
    ]
