# Generated by Django 5.1 on 2025-02-18 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_alter_timelog_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timelogs', to='task_manager.building'),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timelogs', to='task_manager.mark'),
        ),
    ]
