# Generated by Django 5.1 on 2025-05-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_alter_timelog_building_alter_timelog_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Отметьте False для задач, созданных на лету из отчёта'),
        ),
    ]
